// Rufe alle User ab. Zu Beginn sollten keine User in der Datenbank sein. 
###
GET http://localhost/api/publicUsers

// Lege ersten User an, der Administrator ist
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "userID": "admin",
    "firstName": "Udo",
    "lastName": "Müller",
    "password": "123",
    "isAdministrator": true
}

// Rufe den User mit UserID admin ab. 
###
GET http://localhost/api/publicUsers/admin

// Lege zweiten User an. Prüfe UserID sowie den Namen, ob die Angaben korrekt sind.
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "userID": "manfred",
    "firstName": "Susi",
    "lastName": "Sunkist",
    "password": "asdf"
}

// Ändere beim zweiten User den User-Name. Zur Selektion des Users verwende die userID.
###
PUT http://localhost/api/publicUsers/manfred
Content-Type: application/json

{
    "firstName": "Marina",
    "lastName": "Sauerbier"
}

// Rufe alle User ab. Es sollten 2 User zurückgegeben werden.
###
GET http://localhost/api/publicUsers

// Lösche den User mit der User-ID manfred
###
DELETE  http://localhost/api/publicUsers/manfred

###
DELETE  http://localhost/api/publicUsers/admin

// Versuche einen User mit einer bereits existierenden UserID anzulegen
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "userID": "admin",
    "firstName": "Duplicate",
    "lastName": "User",
    "password": "456",
    "isAdministrator": true
}

// Versuche einen nicht existierenden User zu löschen
###
DELETE http://localhost/api/publicUsers/nonexistent_user

// Versuche einen nicht existierenden User zu ändern
###
PUT http://localhost/api/publicUsers/nonexistent_user
Content-Type: application/json

{
    "firstName": "Nobody",
    "lastName": "Here"
}

// Versuche einen User ohne UserID anzulegen
###
POST http://localhost/api/publicUsers
Content-Type: application/json

{
    "firstName": "Missing",
    "lastName": "UserID",
    "password": "789"
}

###
PUT http://localhost/api/publicUsers/manfred
Content-Type: application/json

{
"password" : "asdf"
}

// should be following
# HTTP/1.1 200 OK
# X-Powered-By Express
# Content-Type application/json; charset=utf-8
# Content-Length 153
# ETag W/"99-whWApKwDt2tr907o6ZTWHH+voMA"
# Date Fri, 02 May 2025 18:58:05 GMT
# Connection keep-alive
# Keep-Alive timeout=5
# {
#     "userID" : "manfred",
#     "password" : "asdf",
#     "firstName" : "Susi Sunkist",
#     "lastName" : "Mustermann",
#     "isAdministrator" : false,
#     "__v" : 0,
#     "id" : "681515bd7faab1c39ecf056e"
# }